CREATE TABLE #TIPO ( CD_TIPO INT, DSC_TIPO VARCHAR(50))

CREATE TABLE #VENDAS ( CD_TIPO INT, VAL_TIPO NUMERIC(12,2))

INSERT INTO #TIPO VALUES (1, 'MANUAL')
INSERT INTO #TIPO VALUES (2, 'AUTOMATICO')

INSERT INTO #VENDAS VALUES ( 1, 100.25 )
INSERT INTO #VENDAS VALUES ( 1, 100.25 )
INSERT INTO #VENDAS VALUES ( 1, 100.25 )
INSERT INTO #VENDAS VALUES ( 1, 100.25 )

INSERT INTO #VENDAS VALUES ( 2, 100 )
INSERT INTO #VENDAS VALUES ( 2, 100 )
INSERT INTO #VENDAS VALUES ( 2, 100 )
INSERT INTO #VENDAS VALUES ( 2, 100 )


SELECT GROUPING(T.DSC_TIPO), T.DSC_TIPO, SUM(V.VAL_TIPO) TOTAL
FROM #TIPO T, #VENDAS V
WHERE T.CD_TIPO = V.CD_TIPO
GROUP BY T.DSC_TIPO WITH ROLLUP

SELECT 	CASE GROUPING(T.DSC_TIPO) WHEN 0 THEN T.DSC_TIPO ELSE 'TOTAL' END 	AS TIPO,
	SUM(V.VAL_TIPO) 							AS TOTAL
FROM #TIPO T, #VENDAS V
WHERE T.CD_TIPO = V.CD_TIPO
GROUP BY T.DSC_TIPO WITH ROLLUP


--CUBE CRIA SUBTOTAIS

SELECT GROUPING(T.DSC_TIPO), T.DSC_TIPO, SUM(V.VAL_TIPO) TOTAL
FROM #TIPO T, #VENDAS V
WHERE T.CD_TIPO = V.CD_TIPO
GROUP BY T.DSC_TIPO WITH CUBE

SELECT 	CASE GROUPING(T.DSC_TIPO) WHEN 0 THEN T.DSC_TIPO ELSE 'TOTAL' END 	AS TIPO,
	SUM(V.VAL_TIPO) 							AS TOTAL
FROM #TIPO T, #VENDAS V
WHERE T.CD_TIPO = V.CD_TIPO
GROUP BY T.DSC_TIPO WITH CUBE