--APLICAR ESTE COMENTÁRIO SOMENTE EM PRODUÇÃO (sp_fkeys 'contrato')

ALTER TABLE F_Contratos 
DROP CONSTRAINT R_360
GO
ALTER TABLE F_Vendas_atu
DROP CONSTRAINT R_152_atu
GO
ALTER TABLE F_Vendas_hist
DROP CONSTRAINT R_152_hist
GO
DROP TABLE F_Contratos
GO
DROP TABLE Contrato
GO