select isnumeric(1234)
select isnumeric('1234A')

-- ISNUMERIC CONSIDERA NUMÉRICA A SEQ ABAIXO.
SELECT ISNUMERIC('0000D2')



--ALTERNATIVA PARA ISNUMERIC

SELECT CASE WHEN PATINDEX('%[A-Z]%','0000D2') <> 0 THEN Texto ELSE NUMERICO END

SELECT CASE WHEN PATINDEX('%[A-Z]%',codigo_segmento) = 0 THEN CONVERT(INT,codigo_segmento) ELSE -2 END